### PR TITLE
description about "downward api"

### PR DESCRIPTION
**Pull request by STRRL**

### CODE REVIEW

**Comment by STRRL** [comment]
@YangKeao  PTAL :D

**Comment by YangKeao** [comment]
Is there any detailed description of `Downward API`?

**Comment by STRRL** [comment]
> We will provide something like "Downward API", it means workflow status will be
written into this container as file, so that users could make any conditions based
on workflow status.

How about change description like this?

**Comment by YangKeao** [comment]
@STRRL  I don't know whether the file is a great way. Writing a file to another container seems will not be better than write to stdin.

**Comment by STRRL** [comment]
I think the best way is a pseudo fs like procfs, but it seems not so easy to implement, so I just write into a "static" file.

Comparing with stdin, I think static file:
- more easy to implement, we could just create config map and mount it; I think send bytes to stdin need something like `kubectl exec` 
- it's easier to visible from "god vision", stdin seems not easy to re-access.

**Comment by STRRL** [comment]
Hi @YangKeao, how do you think about this PR, could we merge it? :P

**Pull request merged**
